name: fcm_push_node_interop
author: Alexandr Priezzhev <a@priezz.net>
description: A Dart interface to Firebase Cloud Messaging (FCM) for NodeJS
homepage: https://github.com/priezz/fcm_push_node_interop

version: 1.0.3

environment:
  sdk: '>=2.3.0-dev <3.0.0'

dependencies:
  node_http: ^1.0.0

dev_dependencies:
  build_runner: any
  build_node_compilers: ^0.2.4
  build_test: any
  test: any
